version: '3.8'

services:
  confapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: confapp
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    # For persistent storage of chat history (optional)
    volumes:
      - confapp-data:/app/data

volumes:
  confapp-data: